### ISSUE TITLE
how to use add-in

### ISSUE THREAD

**Issue by tjmahr** [tjmahr/WrapRmd#10]
hey @lorenzwalthert, I saw your tweet here: https://twitter.com/lorenzwalthert/status/1017703674552967168

I've blocked myself from using my twitter account until i finish my dissertation. but since you asked a question about how it works... the add-in only works on highlighted markdown text. the experimental branch is what i use now. it uses commonmark so it does some extra stuff like replace HTML entities.

**Comment by lorenzwalthert** [comment]
Ok, thanks for the explanation and all the best for your dissertation.
