### ISSUE TITLE
problems with wrapping lines containing latex code

### ISSUE THREAD

**Issue by IndrajeetPatil** [tjmahr/WrapRmd#15]
# Before

![image](https://user-images.githubusercontent.com/11330453/102718218-540dc800-42e7-11eb-9a45-70e4c2b285ef.png)

Works as expected

![image](https://user-images.githubusercontent.com/11330453/102718303-b6ff5f00-42e7-11eb-994c-4c8334f6b91b.png)

# After

![image](https://user-images.githubusercontent.com/11330453/102718235-6851c500-42e7-11eb-97db-5dabf65fd13a.png)

But the extra `\` introduced by `WrapRmd` creates problems for rendering the equations:

![image](https://user-images.githubusercontent.com/11330453/102718252-7d2e5880-42e7-11eb-86de-3b434a8175b7.png)

**Comment by tjmahr** [comment]
WrapRmd runs the markdown through common mark which escapes the \’s. I would appreciate any input from people who want to help develop a way of unescaping the backslashes or finding a way to keep common mark from escaping them in the first place.

**Comment by AjayKMehta** [comment]
I think the approach of using a regex for LaTeX similar to what was done for cross-references in [this PR](https://github.com/tjmahr/WrapRmd/pull/17) would work.

``` r
 re_latex <-  "((?!=[$])\\$[^$]*\\$)"
stringr::str_extract("$\alpha + \beta$ is 3", re_latex)
#> [1] "$\alpha + \beta$"
```

<sup>Created on 2021-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Please insert customary joke about solving a problem with regex 😀
