### ISSUE TITLE
Avoid wrapping cross-references

### ISSUE THREAD

**Issue by shirdekel** [tjmahr/WrapRmd#16]
Would you consider adding support for avoiding inserting line breaks into cross-references, as with inline R code?

I'm referring to lines such as `Figure\ \@ref(fig:plot-name)` or `Table\ \@ref(tab:table-name)`.

Adding a line break between`Figure\` and `\@ref(fig:plot-name)` leads to a forced line break in the output.

Happy to attempt a PR.

**Comment by tjmahr** [comment]
Go for a PR 🤓
