### ISSUE TITLE
R version

### ISSUE THREAD

**Issue by jbkunst** [tjmahr/WrapRmd#4]
Hi @tjmahr,

Nice addin. I want try this package but I have no lastest R version so:

```
ERROR: this R is version 3.2.2, package 'WrapRmd' requires R >= 3.2.3
```

Is this really necessary? https://github.com/tjmahr/WrapRmd/blob/master/DESCRIPTION#L7

(I know it is better have all updated but sometimes is not the scenario)

**Comment by tjmahr** [comment]
Hmm. I think devtools auto-populated that field. Good catch

**Comment by jbkunst** [comment]
Thanks @tjmahr!
