### ISSUE TITLE
Support links?

### ISSUE THREAD

**Issue by batpigandme** [tjmahr/WrapRmd#7]
Loving this package! It _does_, however, break links and occasionally formatting when knitting to html (e.g. **bold move** can end up with the asterisks staying in, and no formatting— sorry, I actually can't recreate it with GitHub md). Let me know if you want me to reprex anything!

Again, awesome package!

**Comment by tjmahr** [comment]
First, let me make a quick caveat that I use this on paragraphs of text, not entire documents or on markdown lists or anything else. That said, it sounds like the problem would be this example... which I should fix!

``` r
string <- "
It's very easy to make some words **bold** and a [link to Google!](http://google.com)
"

cat(WrapRmd::str_rmd_wrap(string))
#> 
#> It's very easy to make some words **bold** and a [link to Google!](http://
#> google.com)
```

**Comment by batpigandme** [comment]
Oh that's perfect. Thanks, TJ! I've been only running it on paragraphs, I just have so many links in them that I ended up with a funky mishmash of manually, and 😍 gorgeously (w/ Rmd Wrap add-in) paragraphs in my docs. That'll solve it though!

**Comment by tjmahr** [comment]
I haven't fixed anything yet though!

**Comment by tjmahr** [comment]
I'm thinking of a way to have a package that specializes in markdown parsing handle the link-finding and text-wrapping. I'll update the package if I figure something out.

**Comment by batpigandme** [comment]
Oh, 😂, I thought you were just suggesting I do that as a personal snippet or something!

**Comment by tjmahr** [comment]
I created a new experimental branch. It can be installed with:

```
devtools::install_github("tjmahr/WrapRmd", ref = "experimental")
```

Originally, the package would use `stringr::str_wrap()` which produces pleasing wrapped text. Now I'm using `commonmark::markdown_commonmark(text, width = 80)` which says to take some markdown text and render it as commonmark text that is up 80 characters wide.

The original reprex now yields:

```r
string <- "
It's very easy to make some words **bold** and a [link to Google!](http://google.com)
"

cat(WrapRmd::str_rmd_wrap(string))
#> 
#> It's very easy to make some words **bold** and a [link to
#> Google!](http://google.com)
```

I don't know what other kind of safety measures the commonmark processing might be doing, so I'm going to live with this version for a while and iron out any issues I run into. 

I have already noticed small differences in word wrapping (the word _a_ moved up a line in one example). The commonmark processor tried escaping `!` so the reprex gave `Google\!]`, but I have that fixed too.

**Comment by tjmahr** [comment]
Hmmm, it looks like the commonmark thing converts underscores into asterisks when it won't break things. On the plus side, we can wrap lists now!


``` r
stringo <- "
1. Lorem ipsum dolor sit amet, _consectetur_ adipiscing elit. Vestibulum a `r max(iris$Sepal.Length)`, 
1. __But at least it can do lists!__ viverra nisl at, luctus ante = `r length(letters) * 2 + 100`.
"

cat(WrapRmd::str_rmd_wrap(stringo))
#> 
#> 1.  Lorem ipsum dolor sit amet, *consectetur* adipiscing elit. Vestibulum a
#>     `r max(iris$Sepal.Length)`,
#> 2.  **But at least it can do lists!** viverra nisl at, luctus ante =
#>     `r length(letters) * 2 + 100`.
```

**Comment by IndrajeetPatil** [comment]
This is an awesome RStudio add-in and I've been using it constantly ever since I discovered it!
 
The only issue I face is the one raised above by Mara. If there are URLs, they break during knitting. Should I download the `experimental` branch or have these changes been merged into the `master` branch?

**Comment by tjmahr** [comment]
Try the experimental version. It can be installed like any package from github. I have been using it for a few months and like it but it needs more input from users. 

 devtools::install_github("tjmahr/WrapRmd", ref = "experimental")

**Comment by batpigandme** [comment]
It works!! Thanks @tjmahr!
